Add cursor affinity
pop-os/cosmic-text pull request #62
Opened 2023-01-11 03:17 UTC by rhelmot

This is a breaking change on account of adding a new public field to the Cursor struct.

However, it does significantly improve the user experience with respect to moving the cursor between soft-wrapped lines. The new behavior doesn't _perfectly_ match the rest of the applications on my operating system (ubuntu) but it seems to make the home/end keys as well as up/down at the start or end of lines much nicer.

2023-01-14 14:37 UTC, nicoburns requested changes

2023-01-14 14:37 UTC, nicoburns commented on src/buffer.rs
> +    pub affinity: bool,
I feel like it would be clearer if this was an enum with `Before` and `After` variants instead of a boolean.

2023-01-14 14:37 UTC, nicoburns commented on src/buffer.rs
> +    pub const fn new_affinity(line: usize, index: usize, affinity: bool) -> Self {
Nit: I think `new_with_affinity` or `with_affinity` would be a more idiomatic name for this method.

2023-01-14 17:26 UTC, rhelmot commented
Fixed both.

Side note: I initially reached for #[Derive(Default)] on the enum, but then I realized that you don't actually have a minimum rust version specified in your cargo.toml. Might be nice to add.

2023-01-16 00:17 UTC, rhelmot commented
(from testing, it seems the MSRV should be 1.63)

2023-01-19 16:19 UTC, merged